/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace OpenTransactions.OTAPI {

public class MarketList : Storable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal MarketList(global::System.IntPtr cPtr, bool cMemoryOwn) : base(otapiPINVOKE.MarketList_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MarketList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MarketList() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otapiPINVOKE.delete_MarketList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public uint GetMarketDataCount() {
    uint ret = otapiPINVOKE.MarketList_GetMarketDataCount(swigCPtr);
    return ret;
  }

  public MarketData GetMarketData(uint nIndex) {
    global::System.IntPtr cPtr = otapiPINVOKE.MarketList_GetMarketData(swigCPtr, nIndex);
    MarketData ret = (cPtr == global::System.IntPtr.Zero) ? null : new MarketData(cPtr, false);
    return ret;
  }

  public bool RemoveMarketData(uint nIndexMarketData) {
    bool ret = otapiPINVOKE.MarketList_RemoveMarketData(swigCPtr, nIndexMarketData);
    return ret;
  }

  public bool AddMarketData(MarketData disownObject) {
    bool ret = otapiPINVOKE.MarketList_AddMarketData(swigCPtr, MarketData.getCPtr(disownObject));
    if (otapiPINVOKE.SWIGPendingException.Pending) throw otapiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static MarketList ot_dynamic_cast(Storable pObject) {
    global::System.IntPtr cPtr = otapiPINVOKE.MarketList_ot_dynamic_cast(Storable.getCPtr(pObject));
    MarketList ret = (cPtr == global::System.IntPtr.Zero) ? null : new MarketList(cPtr, false);
    return ret;
  }

}

}
