#ifndef _H_OT_COMMAND_OT
#define _H_OT_COMMAND_OT

#include <algorithm>
#include <string>
#include <vector>


#define OT_COMMAND_OT


using std::map;
using std::string;
using std::vector;


extern int OT_COMMAND_OT accept_from_paymentbox(const string & strMyAcctID, const string & strIndices);
extern int OT_COMMAND_OT accept_from_paymentbox(const string & strMyAcctID, const string & strIndices, const string & strPaymentType);
extern int OT_COMMAND_OT accept_inbox_items(const string & strMyAcctID, const int nItemType, const string & strIndices);
extern int OT_COMMAND_OT details_accept_invoices(const string & strMyAcctID); // Use this function when you want to loop through all accounts and accept all invoices for them.
extern int OT_COMMAND_OT details_accept_invoices(const string & strMyAcctID, const string & strIndices);
extern int OT_COMMAND_OT details_accept_payments(const string & strMyAcctID);
extern int OT_COMMAND_OT details_accept_payments(const string & strMyAcctID, const string & strIndices);
extern int OT_COMMAND_OT details_account_balance(const string & strID);
extern int OT_COMMAND_OT details_cancel_outgoing(const string & strMyNym, const string & strMyAcct, const string & strIndices);
extern string OT_COMMAND_OT details_check_user(const string & strServerID, const string & strMyNymID, const string & strHisNymID);
extern int OT_COMMAND_OT details_clear_expired(const string & strServerID, const string & strMyNymID);
extern int OT_COMMAND_OT details_clear_records(const string & strServerID, const string & strMyNymID, const string & strMyAcctID);
extern int OT_COMMAND_OT details_confirm_plan(const string & strPlan, const int nIndex);
extern int OT_COMMAND_OT details_confirm_smart_contract(string & strSmartContract, const int nIndex);
extern int OT_COMMAND_OT details_create_nym(const int nKeybits, const string & strName, const string & strSourceForNymID, const string & strAltLocation);
extern int OT_COMMAND_OT details_create_offer(const string & strScale, const string & strMinIncrement, const string & strQuantity, const string & strPrice, const bool bSelling, const string & strLifespan);
extern int OT_COMMAND_OT details_del_mail(const string & strMyNymID, const string & strIndices);
extern int OT_COMMAND_OT details_del_outmail(const string & strMyNymID, const string & strIndices);
extern int OT_COMMAND_OT details_deposit(const string & strServerID, const string & strMyAcctID);
extern int OT_COMMAND_OT details_deposit_cheque(const string & strServerID, const string & strMyAcct, const string & strMyNymID, const string & strInstrument, const string & strType);
extern int OT_COMMAND_OT details_deposit_purse(const string & strServerID, const string & strMyAcct, const string & strFromNymID, const string & strInstrument, const string & strIndices);
extern int OT_COMMAND_OT details_discard_incoming(const string & strServer, const string & strMyNym, const string & strIndices);
extern int OT_COMMAND_OT details_download_box_receipt(const string & strID, const int nBoxType);
extern int OT_COMMAND_OT details_download_contract(const string & strServerID, const string & strNymID, const string & strContractID);
extern int OT_COMMAND_OT details_exchange_basket(const string & strServer, const string & strNym, const string & strAcct, const string & strBasketType);
extern string OT_COMMAND_OT details_export_cash(const string & strServerID, const string & strFromNymID, const string & strAssetTypeID, string & strHisNymID, const string & strIndices, const bool bPasswordProtected, string & strRetainedCopy);
extern string OT_COMMAND_OT details_export_nym(const string & strNymID);
extern string OT_COMMAND_OT details_get_nym_market_offers(const string & strServerID, const string & strNymID);
extern int OT_COMMAND_OT details_import_cash(const string & strInstrument);
extern bool OT_COMMAND_OT details_import_nym(const string & strNymImportFile, string & strOutNymID);
extern int OT_COMMAND_OT details_import_purse(const string & strInstrument, const bool bHasPassword, const string & strPurseOwner);
extern int OT_COMMAND_OT details_kill_offer(const string & strServerID, const string & strNymID, const string & strAcctID, const string & strTransNum);
extern int OT_COMMAND_OT details_new_basket(const string & strServer, const string & strNym);
extern int OT_COMMAND_OT details_nym_stat(const string & strID);
extern int OT_COMMAND_OT details_pay_dividend(const string & strAmount, const string & strMemo);
extern int OT_COMMAND_OT details_propose_plan(const string & strServerID, const string & strMyNymID, const string & strMyAcctID, const string & strHisNymID, const string & strHisAcctID, const string & strDates, const string & strConsideration, const string & strInitialPayment, const string & strPaymentPlan, const string & strExpiry);
extern bool OT_COMMAND_OT details_refresh_nym(const string & strServerID, const string & strMyNymID);
extern bool OT_COMMAND_OT details_refresh_nym(const string & strServerID, const string & strMyNymID, const bool bForceDownload);
extern bool OT_COMMAND_OT details_refresh_nym(const string & strServerID, const string & strMyNymID, bool & bWasMsgSent, const bool bForceDownload);
extern int OT_COMMAND_OT details_send_cash(string & strResponse, const string & strServerID, const string & strAssetTypeID, const string & strMyNymID, const string & strMyAcctID, string & strHisNymID, const string & strMemo, const string & strAmount, string & strIndices, const bool bPasswordProtected);
extern int OT_COMMAND_OT details_send_transfer(const string & strMyAcctID, const string & strHisAcctID, const string & strAmount, const string & strNote);
extern int OT_COMMAND_OT details_show_basket();
extern int OT_COMMAND_OT details_show_credential(const string & strMyNymID, const string & strCredID);
extern bool OT_COMMAND_OT details_show_credentials(const string & strMyNymID);
extern int OT_COMMAND_OT details_show_expired(const string & strServerID, const string & strMyNymID, const int nIndex);
extern int OT_COMMAND_OT details_show_expired(const string & strServerID, const string & strMyNymID, const int nIndex, const string & strExpiredBox);
extern int OT_COMMAND_OT details_show_expired_records(const string & strServerID, const string & strMyNymID);
extern int OT_COMMAND_OT details_show_market_offers(const string & strServerID, const string & strMarketID);
extern int OT_COMMAND_OT details_show_nym_offers(const string & strServerID, const string & strNymID);
extern int OT_COMMAND_OT details_show_record(const string & strServerID, const string & strMyNymID, const string & strMyAcctID, const int nIndex);
extern int OT_COMMAND_OT details_show_record(const string & strServerID, const string & strMyNymID, const string & strMyAcctID, const int nIndex, const string & strRecordBox);
extern int OT_COMMAND_OT details_show_records(const string & strServerID, const string & strMyNymID, const string & strMyAcctID);
extern int OT_COMMAND_OT details_stat_account(const string & strID);
extern int OT_COMMAND_OT details_trigger_clause(const string & strServerID, const string & strMyNymID, const string & strTransNum, const string & strClause, const string & strParam);
extern int OT_COMMAND_OT details_withdraw_cash(const string & strMyAcctID, const int64_t lAmount);
extern int OT_COMMAND_OT details_withdraw_voucher(string & strOutput);
extern int OT_COMMAND_OT details_write_cheque(string & strCheque, const bool bIsInvoice); // strCheque is output.
extern int OT_COMMAND_OT download_acct_files();
extern string OT_COMMAND_OT find_masterID_for_subcred(const string & strMyNymID, const string & strInputID);
extern string OT_COMMAND_OT find_revokedID_for_subcred(const string & strMyNymID, const string & strInputID);
extern int OT_COMMAND_OT handle_payment_index(const string & strMyAcctID, const int nIndex); // (If nIndex is -1, then it will ask user to paste an invoice.);
extern int OT_COMMAND_OT handle_payment_index(const string & strMyAcctID, const int nIndex, const string & strPaymentType); // (If nIndex is -1, then it will ask user to paste an invoice.);
extern int OT_COMMAND_OT handle_payment_index(const string & strMyAcctID, const int nIndex, const string & strPaymentType, const string & strInbox); // (If nIndex is -1, then it will ask user to paste an invoice.);
extern int OT_COMMAND_OT impl_show_market_offers(string & strMarket);
extern int OT_COMMAND_OT loadMarketList(const string & strerverID);
extern int OT_COMMAND_OT loadMarketOffers(const string & strerverID, const string & strMarketID);
extern int OT_COMMAND_OT main_accept_all();
extern int OT_COMMAND_OT main_accept_inbox();
extern int OT_COMMAND_OT main_accept_invoices();
extern int OT_COMMAND_OT main_accept_money();
extern int OT_COMMAND_OT main_accept_payments();
extern int OT_COMMAND_OT main_accept_receipts();
extern int OT_COMMAND_OT main_accept_transfers();
extern int OT_COMMAND_OT main_add_asset();
extern int OT_COMMAND_OT main_add_server();
extern int OT_COMMAND_OT main_add_signature();
extern int OT_COMMAND_OT main_adjust_usage_credits();
extern int OT_COMMAND_OT main_balance();
extern int OT_COMMAND_OT main_cancel_outgoing();
extern int OT_COMMAND_OT main_change_passphrase();
extern int OT_COMMAND_OT main_check_user();
extern int OT_COMMAND_OT main_clear_expired();
extern int OT_COMMAND_OT main_clear_records();
extern int OT_COMMAND_OT main_confirm(); // smart contract and payment plan
extern int OT_COMMAND_OT main_create_acct();
extern int OT_COMMAND_OT main_create_asset_contract();
extern int OT_COMMAND_OT main_create_nym();
extern int OT_COMMAND_OT main_create_offer();
extern int OT_COMMAND_OT main_create_server_contract();
extern int OT_COMMAND_OT main_decode();
extern int OT_COMMAND_OT main_decrypt();
extern int OT_COMMAND_OT main_del_mail();
extern int OT_COMMAND_OT main_del_outmail();
extern int OT_COMMAND_OT main_deposit();
extern int OT_COMMAND_OT main_discard_incoming();
extern int OT_COMMAND_OT main_dl_acct_files();
extern int OT_COMMAND_OT main_download_contract();
extern int OT_COMMAND_OT main_edit_account();
extern int OT_COMMAND_OT main_edit_asset();
extern int OT_COMMAND_OT main_edit_nym();
extern int OT_COMMAND_OT main_edit_server();
extern int OT_COMMAND_OT main_encode();
extern int OT_COMMAND_OT main_encrypt();
extern int OT_COMMAND_OT main_exchange_basket();
extern int OT_COMMAND_OT main_export_cash();
extern int OT_COMMAND_OT main_export_nym();
extern int OT_COMMAND_OT main_get_box_receipt();
extern int OT_COMMAND_OT main_get_market_list();
extern int OT_COMMAND_OT main_get_market_offers();
extern int OT_COMMAND_OT main_get_nym_market_offers();
extern int OT_COMMAND_OT main_import_cash();
extern int OT_COMMAND_OT main_import_nym();
extern int OT_COMMAND_OT main_issue_asset();
extern int OT_COMMAND_OT main_kill_offer();
extern int OT_COMMAND_OT main_kill_plan();
extern int OT_COMMAND_OT main_new_basket();
extern int OT_COMMAND_OT main_new_credential();
extern int OT_COMMAND_OT main_new_symmetric_key();
extern int OT_COMMAND_OT main_nym_stat();
extern int OT_COMMAND_OT main_password_decrypt();
extern int OT_COMMAND_OT main_password_encrypt();
extern int OT_COMMAND_OT main_pay_dividend();
extern int OT_COMMAND_OT main_payinvoice();
extern int OT_COMMAND_OT main_propose_plan(); // payment plan -- called by recipient. (Who generates the proposal.);
extern int OT_COMMAND_OT main_refresh_all();
extern int OT_COMMAND_OT main_refresh_nym();
extern int OT_COMMAND_OT main_register_nym();
extern int OT_COMMAND_OT main_revoke_credential();
extern int OT_COMMAND_OT main_sendcash();
extern int OT_COMMAND_OT main_sendcheque();
extern int OT_COMMAND_OT main_sendinvoice();
extern int OT_COMMAND_OT main_sendmsg();
extern int OT_COMMAND_OT main_sendvoucher();
extern int OT_COMMAND_OT main_show_basket();
extern int OT_COMMAND_OT main_show_credential();
extern int OT_COMMAND_OT main_show_credentials();
extern int OT_COMMAND_OT main_show_expired();
extern int OT_COMMAND_OT main_show_inbox();
extern int OT_COMMAND_OT main_show_incoming();
extern int OT_COMMAND_OT main_show_mail();
extern int OT_COMMAND_OT main_show_market_list();
extern int OT_COMMAND_OT main_show_market_offers();
extern int OT_COMMAND_OT main_show_mint();
extern int OT_COMMAND_OT main_show_nym_offers();
extern int OT_COMMAND_OT main_show_outbox();
extern int OT_COMMAND_OT main_show_outgoing();
extern int OT_COMMAND_OT main_show_outmail();
extern int OT_COMMAND_OT main_show_outpayment();
extern int OT_COMMAND_OT main_show_payment();
extern int OT_COMMAND_OT main_show_payments_inbox();
extern int OT_COMMAND_OT main_show_purse();
extern int OT_COMMAND_OT main_show_records();
extern int OT_COMMAND_OT main_sign_contract();
extern int OT_COMMAND_OT main_stat();
extern int OT_COMMAND_OT main_stat_acct();
extern int OT_COMMAND_OT main_transfer();
extern int OT_COMMAND_OT main_trigger_clause();
extern int OT_COMMAND_OT main_verify_last_receipt();
extern int OT_COMMAND_OT main_verify_signature();
extern int OT_COMMAND_OT main_withdraw_cash();
extern int OT_COMMAND_OT main_withdraw_voucher();
extern int OT_COMMAND_OT main_write_cheque();
extern int OT_COMMAND_OT main_write_invoice();
extern bool OT_COMMAND_OT purse_get_indices_or_amount(const string & strServerID, const string & strAssetTypeID, const string & strMyNymID, int64_t & lAmount, string & strIndices); // If strIndices is input, lAmount is output. (And vice-versa.);
extern int OT_COMMAND_OT show_mail_message(const string & strMyNymID, const int nIndex, const bool bShowContents);
extern int OT_COMMAND_OT show_outmail_message(const string & strMyNymID, const int nIndex, const bool bShowContents);
extern bool OT_COMMAND_OT show_outpayment(const string & strMyNym, const int nIndex);
extern bool OT_COMMAND_OT show_outpayment(const string & strMyNym, const int nIndex, const bool bShowInFull);
extern bool OT_COMMAND_OT show_unconfirmed_parties(const string & strSmartContract);
extern bool OT_COMMAND_OT show_unconfirmed_parties(const string & strSmartContract, int & nPartyCount);
extern int OT_COMMAND_OT stat_accounts();
extern int OT_COMMAND_OT stat_assets();
extern int OT_COMMAND_OT stat_basket_accounts();
extern int OT_COMMAND_OT stat_basket_accounts(const string & strServer, const string & strNym);
extern int OT_COMMAND_OT stat_basket_accounts(const string & strServer, const string & strNym, const bool bFilter, const string & strBasketType);
extern int OT_COMMAND_OT stat_nyms();
extern bool OT_COMMAND_OT stat_partyaccount(const string & strSmartContract, const string & strPartyName, const string & strAcctName, const int nCurrentAccount);
extern bool OT_COMMAND_OT stat_partyaccount_index(const string & strSmartContract, const string & strPartyName, const int nCurrentAccount);
extern bool OT_COMMAND_OT stat_partyaccounts(const string & strSmartContract, const string & strPartyName, const int nDepth);
extern int OT_COMMAND_OT stat_partyagent(const string & strSmartContract, const string & strPartyName, const string & strAgentName, const int nIndex);
extern int OT_COMMAND_OT stat_partyagent_index(const string & strSmartContract, const string & strPartyName, const int nCurrentAgent);
extern int OT_COMMAND_OT stat_partyagents(const string & strSmartContract, const string & strPartyName, const int nDepth);
extern int OT_COMMAND_OT stat_servers();
extern bool OT_COMMAND_OT withdraw_and_send_cash(const string & strMyAcctID, string & strHisNymID, const string & strMemo, const string & strAmount);

#endif
