/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class OTNameLookup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OTNameLookup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OTNameLookup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_OTNameLookup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    otapiJNI.OTNameLookup_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    otapiJNI.OTNameLookup_change_ownership(this, swigCPtr, true);
  }

  public OTNameLookup() {
    this(otapiJNI.new_OTNameLookup(), true);
    otapiJNI.OTNameLookup_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String GetNymName(String str_id, SWIGTYPE_p_std__string p_server_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetNymName__SWIG_0(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_server_id)) : otapiJNI.OTNameLookup_GetNymNameSwigExplicitOTNameLookup__SWIG_0(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_server_id));
  }

  public String GetNymName(String str_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetNymName__SWIG_1(swigCPtr, this, str_id) : otapiJNI.OTNameLookup_GetNymNameSwigExplicitOTNameLookup__SWIG_1(swigCPtr, this, str_id);
  }

  public String GetAcctName(String str_id, SWIGTYPE_p_std__string p_nym_id, SWIGTYPE_p_std__string p_server_id, SWIGTYPE_p_std__string p_asset_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetAcctName__SWIG_0(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id), SWIGTYPE_p_std__string.getCPtr(p_server_id), SWIGTYPE_p_std__string.getCPtr(p_asset_id)) : otapiJNI.OTNameLookup_GetAcctNameSwigExplicitOTNameLookup__SWIG_0(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id), SWIGTYPE_p_std__string.getCPtr(p_server_id), SWIGTYPE_p_std__string.getCPtr(p_asset_id));
  }

  public String GetAcctName(String str_id, SWIGTYPE_p_std__string p_nym_id, SWIGTYPE_p_std__string p_server_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetAcctName__SWIG_1(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id), SWIGTYPE_p_std__string.getCPtr(p_server_id)) : otapiJNI.OTNameLookup_GetAcctNameSwigExplicitOTNameLookup__SWIG_1(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id), SWIGTYPE_p_std__string.getCPtr(p_server_id));
  }

  public String GetAcctName(String str_id, SWIGTYPE_p_std__string p_nym_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetAcctName__SWIG_2(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id)) : otapiJNI.OTNameLookup_GetAcctNameSwigExplicitOTNameLookup__SWIG_2(swigCPtr, this, str_id, SWIGTYPE_p_std__string.getCPtr(p_nym_id));
  }

  public String GetAcctName(String str_id) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetAcctName__SWIG_3(swigCPtr, this, str_id) : otapiJNI.OTNameLookup_GetAcctNameSwigExplicitOTNameLookup__SWIG_3(swigCPtr, this, str_id);
  }

  public String GetAddressName(String str_address) {
    return (getClass() == OTNameLookup.class) ? otapiJNI.OTNameLookup_GetAddressName(swigCPtr, this, str_address) : otapiJNI.OTNameLookup_GetAddressNameSwigExplicitOTNameLookup(swigCPtr, this, str_address);
  }

}
