/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class OTRecord {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected OTRecord(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OTRecord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_OTRecord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void SetSpecialMail(boolean bIsSpecial) {
    otapiJNI.OTRecord_SetSpecialMail__SWIG_0(swigCPtr, this, bIsSpecial);
  }

  public void SetSpecialMail() {
    otapiJNI.OTRecord_SetSpecialMail__SWIG_1(swigCPtr, this);
  }

  public boolean IsSpecialMail() {
    return otapiJNI.OTRecord_IsSpecialMail(swigCPtr, this);
  }

  public boolean IsPending() {
    return otapiJNI.OTRecord_IsPending(swigCPtr, this);
  }

  public boolean IsOutgoing() {
    return otapiJNI.OTRecord_IsOutgoing(swigCPtr, this);
  }

  public boolean IsRecord() {
    return otapiJNI.OTRecord_IsRecord(swigCPtr, this);
  }

  public boolean IsReceipt() {
    return otapiJNI.OTRecord_IsReceipt(swigCPtr, this);
  }

  public boolean IsMail() {
    return otapiJNI.OTRecord_IsMail(swigCPtr, this);
  }

  public boolean IsTransfer() {
    return otapiJNI.OTRecord_IsTransfer(swigCPtr, this);
  }

  public boolean IsCheque() {
    return otapiJNI.OTRecord_IsCheque(swigCPtr, this);
  }

  public boolean IsInvoice() {
    return otapiJNI.OTRecord_IsInvoice(swigCPtr, this);
  }

  public boolean IsVoucher() {
    return otapiJNI.OTRecord_IsVoucher(swigCPtr, this);
  }

  public boolean IsContract() {
    return otapiJNI.OTRecord_IsContract(swigCPtr, this);
  }

  public boolean IsPaymentPlan() {
    return otapiJNI.OTRecord_IsPaymentPlan(swigCPtr, this);
  }

  public boolean IsCash() {
    return otapiJNI.OTRecord_IsCash(swigCPtr, this);
  }

  public boolean HasContents() {
    return otapiJNI.OTRecord_HasContents(swigCPtr, this);
  }

  public boolean HasMemo() {
    return otapiJNI.OTRecord_HasMemo(swigCPtr, this);
  }

  public boolean IsExpired() {
    return otapiJNI.OTRecord_IsExpired(swigCPtr, this);
  }

  public boolean IsCanceled() {
    return otapiJNI.OTRecord_IsCanceled(swigCPtr, this);
  }

  public void SetExpired() {
    otapiJNI.OTRecord_SetExpired(swigCPtr, this);
  }

  public void SetCanceled() {
    otapiJNI.OTRecord_SetCanceled(swigCPtr, this);
  }

  public SWIGTYPE_p_time64_t GetValidFrom() {
    return new SWIGTYPE_p_time64_t(otapiJNI.OTRecord_GetValidFrom(swigCPtr, this), true);
  }

  public SWIGTYPE_p_time64_t GetValidTo() {
    return new SWIGTYPE_p_time64_t(otapiJNI.OTRecord_GetValidTo(swigCPtr, this), true);
  }

  public void SetDateRange(SWIGTYPE_p_time64_t tValidFrom, SWIGTYPE_p_time64_t tValidTo) {
    otapiJNI.OTRecord_SetDateRange(swigCPtr, this, SWIGTYPE_p_time64_t.getCPtr(tValidFrom), SWIGTYPE_p_time64_t.getCPtr(tValidTo));
  }

  public boolean CanDeleteRecord() {
    return otapiJNI.OTRecord_CanDeleteRecord(swigCPtr, this);
  }

  public boolean CanAcceptIncoming() {
    return otapiJNI.OTRecord_CanAcceptIncoming(swigCPtr, this);
  }

  public boolean CanDiscardIncoming() {
    return otapiJNI.OTRecord_CanDiscardIncoming(swigCPtr, this);
  }

  public boolean CanCancelOutgoing() {
    return otapiJNI.OTRecord_CanCancelOutgoing(swigCPtr, this);
  }

  public boolean CanDiscardOutgoingCash() {
    return otapiJNI.OTRecord_CanDiscardOutgoingCash(swigCPtr, this);
  }

  public boolean CancelOutgoing(String str_via_acct) {
    return otapiJNI.OTRecord_CancelOutgoing(swigCPtr, this, str_via_acct);
  }

  public boolean AcceptIncomingInstrument(String str_into_acct) {
    return otapiJNI.OTRecord_AcceptIncomingInstrument(swigCPtr, this, str_into_acct);
  }

  public boolean AcceptIncomingTransfer() {
    return otapiJNI.OTRecord_AcceptIncomingTransfer(swigCPtr, this);
  }

  public boolean AcceptIncomingReceipt() {
    return otapiJNI.OTRecord_AcceptIncomingReceipt(swigCPtr, this);
  }

  public boolean DiscardIncoming() {
    return otapiJNI.OTRecord_DiscardIncoming(swigCPtr, this);
  }

  public boolean DeleteRecord() {
    return otapiJNI.OTRecord_DeleteRecord(swigCPtr, this);
  }

  public boolean DiscardOutgoingCash() {
    return otapiJNI.OTRecord_DiscardOutgoingCash(swigCPtr, this);
  }

  public int GetBoxIndex() {
    return otapiJNI.OTRecord_GetBoxIndex(swigCPtr, this);
  }

  public void SetBoxIndex(int nBoxIndex) {
    otapiJNI.OTRecord_SetBoxIndex(swigCPtr, this, nBoxIndex);
  }

  public int GetMethodID() {
    return otapiJNI.OTRecord_GetMethodID(swigCPtr, this);
  }

  public void SetMethodID(int nMethodID) {
    otapiJNI.OTRecord_SetMethodID(swigCPtr, this, nMethodID);
  }

  public String GetMsgID() {
    return otapiJNI.OTRecord_GetMsgID(swigCPtr, this);
  }

  public void SetMsgID(String str_id) {
    otapiJNI.OTRecord_SetMsgID(swigCPtr, this, str_id);
  }

  public String GetMsgType() {
    return otapiJNI.OTRecord_GetMsgType(swigCPtr, this);
  }

  public void SetMsgType(String str_type) {
    otapiJNI.OTRecord_SetMsgType(swigCPtr, this, str_type);
  }

  public String GetMsgTypeDisplay() {
    return otapiJNI.OTRecord_GetMsgTypeDisplay(swigCPtr, this);
  }

  public void SetMsgTypeDisplay(String str_type) {
    otapiJNI.OTRecord_SetMsgTypeDisplay(swigCPtr, this, str_type);
  }

  public long GetTransactionNum() {
    return otapiJNI.OTRecord_GetTransactionNum(swigCPtr, this);
  }

  public void SetTransactionNum(long lTransNum) {
    otapiJNI.OTRecord_SetTransactionNum(swigCPtr, this, lTransNum);
  }

  public long GetTransNumForDisplay() {
    return otapiJNI.OTRecord_GetTransNumForDisplay(swigCPtr, this);
  }

  public void SetTransNumForDisplay(long lTransNum) {
    otapiJNI.OTRecord_SetTransNumForDisplay(swigCPtr, this, lTransNum);
  }

  public int GetRecordType() {
    return otapiJNI.OTRecord_GetRecordType(swigCPtr, this);
  }

  public String GetServerID() {
    return otapiJNI.OTRecord_GetServerID(swigCPtr, this);
  }

  public String GetAssetID() {
    return otapiJNI.OTRecord_GetAssetID(swigCPtr, this);
  }

  public String GetCurrencyTLA() {
    return otapiJNI.OTRecord_GetCurrencyTLA(swigCPtr, this);
  }

  public String GetNymID() {
    return otapiJNI.OTRecord_GetNymID(swigCPtr, this);
  }

  public String GetAccountID() {
    return otapiJNI.OTRecord_GetAccountID(swigCPtr, this);
  }

  public String GetAddress() {
    return otapiJNI.OTRecord_GetAddress(swigCPtr, this);
  }

  public String GetOtherNymID() {
    return otapiJNI.OTRecord_GetOtherNymID(swigCPtr, this);
  }

  public String GetOtherAccountID() {
    return otapiJNI.OTRecord_GetOtherAccountID(swigCPtr, this);
  }

  public String GetOtherAddress() {
    return otapiJNI.OTRecord_GetOtherAddress(swigCPtr, this);
  }

  public String GetName() {
    return otapiJNI.OTRecord_GetName(swigCPtr, this);
  }

  public String GetDate() {
    return otapiJNI.OTRecord_GetDate(swigCPtr, this);
  }

  public String GetAmount() {
    return otapiJNI.OTRecord_GetAmount(swigCPtr, this);
  }

  public String GetInstrumentType() {
    return otapiJNI.OTRecord_GetInstrumentType(swigCPtr, this);
  }

  public String GetMemo() {
    return otapiJNI.OTRecord_GetMemo(swigCPtr, this);
  }

  public String GetContents() {
    return otapiJNI.OTRecord_GetContents(swigCPtr, this);
  }

  public void SetOtherNymID(String str_ID) {
    otapiJNI.OTRecord_SetOtherNymID(swigCPtr, this, str_ID);
  }

  public void SetOtherAccountID(String str_ID) {
    otapiJNI.OTRecord_SetOtherAccountID(swigCPtr, this, str_ID);
  }

  public void SetAddress(String str_Address) {
    otapiJNI.OTRecord_SetAddress(swigCPtr, this, str_Address);
  }

  public void SetOtherAddress(String str_Address) {
    otapiJNI.OTRecord_SetOtherAddress(swigCPtr, this, str_Address);
  }

  public void SetMemo(String str_memo) {
    otapiJNI.OTRecord_SetMemo(swigCPtr, this, str_memo);
  }

  public void SetContents(String str_contents) {
    otapiJNI.OTRecord_SetContents(swigCPtr, this, str_contents);
  }

  public boolean HasInitialPayment() {
    return otapiJNI.OTRecord_HasInitialPayment(swigCPtr, this);
  }

  public boolean HasPaymentPlan() {
    return otapiJNI.OTRecord_HasPaymentPlan(swigCPtr, this);
  }

  public SWIGTYPE_p_time64_t GetInitialPaymentDate() {
    return new SWIGTYPE_p_time64_t(otapiJNI.OTRecord_GetInitialPaymentDate(swigCPtr, this), true);
  }

  public SWIGTYPE_p_time64_t GetPaymentPlanStartDate() {
    return new SWIGTYPE_p_time64_t(otapiJNI.OTRecord_GetPaymentPlanStartDate(swigCPtr, this), true);
  }

  public SWIGTYPE_p_time64_t GetTimeBetweenPayments() {
    return new SWIGTYPE_p_time64_t(otapiJNI.OTRecord_GetTimeBetweenPayments(swigCPtr, this), true);
  }

  public long GetInitialPaymentAmount() {
    return otapiJNI.OTRecord_GetInitialPaymentAmount(swigCPtr, this);
  }

  public long GetPaymentPlanAmount() {
    return otapiJNI.OTRecord_GetPaymentPlanAmount(swigCPtr, this);
  }

  public int GetMaximumNoPayments() {
    return otapiJNI.OTRecord_GetMaximumNoPayments(swigCPtr, this);
  }

  public boolean FormatAmount(SWIGTYPE_p_std__string str_output) {
    return otapiJNI.OTRecord_FormatAmount(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(str_output));
  }

  public boolean FormatDescription(SWIGTYPE_p_std__string str_output) {
    return otapiJNI.OTRecord_FormatDescription(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(str_output));
  }

  public boolean FormatShortMailDescription(SWIGTYPE_p_std__string str_output) {
    return otapiJNI.OTRecord_FormatShortMailDescription(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(str_output));
  }

  public boolean FormatMailSubject(SWIGTYPE_p_std__string str_output) {
    return otapiJNI.OTRecord_FormatMailSubject(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(str_output));
  }

  public OTRecord(String str_server_id, String str_asset_id, String str_currency_tla, String str_nym_id, String str_account_id, String str_name, String str_date, String str_amount, String str_type, boolean bIsPending, boolean bIsOutgoing, boolean bIsRecord, boolean bIsReceipt, int eRecordType) {
    this(otapiJNI.new_OTRecord(str_server_id, str_asset_id, str_currency_tla, str_nym_id, str_account_id, str_name, str_date, str_amount, str_type, bIsPending, bIsOutgoing, bIsRecord, bIsReceipt, eRecordType), true);
  }

  public final static class OTRecordType {
    public final static int Mail = otapiJNI.OTRecord_Mail_get();
    public final static int Transfer = otapiJNI.OTRecord_Transfer_get();
    public final static int Receipt = otapiJNI.OTRecord_Receipt_get();
    public final static int Instrument = otapiJNI.OTRecord_Instrument_get();
    public final static int ErrorState = otapiJNI.OTRecord_ErrorState_get();
  }

}
