/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class VectorUnsignedChar {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorUnsignedChar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorUnsignedChar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_VectorUnsignedChar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorUnsignedChar() {
    this(otapiJNI.new_VectorUnsignedChar__SWIG_0(), true);
  }

  public VectorUnsignedChar(long n) {
    this(otapiJNI.new_VectorUnsignedChar__SWIG_1(n), true);
  }

  public long size() {
    return otapiJNI.VectorUnsignedChar_size(swigCPtr, this);
  }

  public long capacity() {
    return otapiJNI.VectorUnsignedChar_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    otapiJNI.VectorUnsignedChar_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return otapiJNI.VectorUnsignedChar_isEmpty(swigCPtr, this);
  }

  public void clear() {
    otapiJNI.VectorUnsignedChar_clear(swigCPtr, this);
  }

  public void add(short x) {
    otapiJNI.VectorUnsignedChar_add(swigCPtr, this, x);
  }

  public short get(int i) {
    return otapiJNI.VectorUnsignedChar_get(swigCPtr, this, i);
  }

  public void set(int i, short val) {
    otapiJNI.VectorUnsignedChar_set(swigCPtr, this, i, val);
  }

}
