/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opentransactions.otapi;

public class WrapTimeT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected WrapTimeT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WrapTimeT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        otapiJNI.delete_WrapTimeT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WrapTimeT() {
    this(otapiJNI.new_WrapTimeT(), true);
  }

  public long getTime() {
    return otapiJNI.WrapTimeT_getTime(swigCPtr, this);
  }

  public void setTime(long _time) {
    otapiJNI.WrapTimeT_setTime(swigCPtr, this, _time);
  }

}
