/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_OTAPI_WRAP_H_
#define SWIG_OTAPI_WRAP_H_

class SwigDirector_OTNameLookup : public OTNameLookup, public Swig::Director {

public:
    SwigDirector_OTNameLookup(zval *self TSRMLS_DC);
    virtual ~SwigDirector_OTNameLookup();
    virtual std::string GetNymName(std::string const &str_id, std::string const *p_server_id = NULL) const;
    virtual std::string GetAcctName(std::string const &str_id, std::string const *p_nym_id = NULL, std::string const *p_server_id = NULL, std::string const *p_asset_id = NULL) const;
    virtual std::string GetAddressName(std::string const &str_address) const;
};

#endif
